config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help', to: 'static_pages#help'
  get  '/home', to: 'static_pages#home'
  get  '/about', to: 'static_pages#about'
  get  '/data', to: 'generation_data#data'
  get  '/new', to: 'generation_data#new'
  get  '/create', to: 'generation_data#create'
  resources :generation_data
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/generation_datum.rb
class GenerationDatum < ApplicationRecord
  validates :seed, uniqueness: { scope: [:width ,:height, :river_length]}
  validates :seed, presence: true, numericality: {only_integer: true}
  validates :width, presence: true, numericality: {greater_than: 0, only_integer: true}
  validates :height, presence: true, numericality: {greater_than: 0, only_integer: true}
  validates :river_length, presence: true, numericality: {greater_than: -1, only_integer: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "Hyello you stinky lizard. Go eat a fly, ugly."   
  end

end

app/controllers/generation_data_controller.rb
class GenerationDataController < ApplicationController
	def data
		index()
	end
	def index
		@settings = GenerationDatum.all
	end
	def new
		@datum = GenerationDatum.new
	end
	def create
    		@datum = GenerationDatum.new(datum_params)    # Not the final implementation!
    		if @datum.save
      			redirect_to data_path
    		else
		      render 'new'
		end
	end
	private
    		def datum_params
      			params.require(:generation_datum).permit(:seed, :width, :height,
                                   :river_length)
    		end
end

app/controllers/image_controller.rb
require 'chunky_png'

#i*j+j*i
#i*i+j*j
#i*j+j*j
#i*j+i*i
#i*j
#i+j
#(mapTo255(i*j+j*i, 0, 255)*r)%255

#if(i-j < 5 && -5 < i-j)
#	v=v-0.25*(i-j).abs
#end

class ImageController
        attr_accessor :image_data
        attr_accessor :image_width
        attr_accessor :image_height
        attr_accessor :randomNum

	def initialize()
		@image_data = Hash.new(0)
		@image_width = 0
		@image_height = 0
		@randomNum = 1
	end
	def generateImage(width, height)
		self.randomNum = (1..4).to_a.shuffle.first
		self.image_data = Hash.new(0)
		self.image_width = width
		self.image_height = height
		generateBaseData()
		#for i in (0..50)
		#	randomRiverCarving((1..(height-1)).to_a.shuffle.first,(1..(width-1)).to_a.shuffle.first)
		#end
		return transferDataToImage()
	end
	def generateBaseData()
		for row in (0..(image_width-1))
			for column in (0..(image_height-1))
				value= calculateValueAtPixel(row, column)
				image_data[[row,column]]= value
			end
		end
	end

	def calculateMinMaxOfData()
		max=min=image_data[[0,0]]
		for row in (0..(image_width-1))
			for column in (0..(image_height-1))
				value = image_data[[row, column]]
				if(value>max) 
					max=value
				elsif(value<min) 
					min=value
				end
			end
		end
		return min, max
	end
	def transferDataToImage()
		min, max = calculateMinMaxOfData()
           	png = ChunkyPNG::Image.new(image_width, image_height, ChunkyPNG::Color::TRANSPARENT)
		for row in (0..(image_width-1))
			for column in (0..(image_height-1))
				v= image_data[[row,column]]
				grey = (ImageController.mapTo255(v, min, max))%255
				colorArr = ImageController.smootherCalcColorGradient(grey)
				png[row,column] = ChunkyPNG::Color.rgba(colorArr[0], colorArr[1], colorArr[2], 255)
			end
		end
		return [png, randomNum]

	end

	def calculateValueAtPixel(row, column)
		output = Math.sin(column/(randomNum*Math::PI))
		output+= Math.cos(row/(2*randomNum*Math::PI))*Math.cos(row/(0.75*randomNum*Math::PI))
		output += calculateValueShiftAtPixel(row, column)
		return output
	end
	def calculateValueShiftAtPixel(row, column)
		if(column-row < 5 || 5 < column-row)
			return -0.05*(column-row)
		end
		return 0
	end
	def calculateValueShiftAtPixelAlt(row, column)
		if( (column-row).abs < 5)
			return -0.05*(column-row)
		end
		return 0
	end
	def randomRiverCarving(row, column)
		path = Array.new()
		currentData = image_data[[row,column]]
		nextPos = [row,column]
		while(true)
			options = Array.new()
			for arr in findNeighbors(nextPos[0], nextPos[1])
				if(currentData < image_data[arr])
					options.push(arr)
				end
			end
			if(options.empty?)
				break
			end
			nextPos = options.shuffle.first
			path.push(nextPos)
			currentData = image_data[nextPos]
		end
		for arr in path
			for pos in findNeighbors(arr[0], arr[1])
				image_data[pos]-= ((image_data[pos]).abs)*0.2
			end
			image_data[arr]-= ((image_data[arr]).abs)*0.4
		end
	end
	def randomFlowCarving(row, column)
		currentData = image_data[[row,column]]
		for arr in findNeighbors(row, column)
			if(currentData < image_data[arr])
				randomFlowCarving(arr[0],arr[1])
			end
		end
		for pos in findNeighbors(arr[0], arr[1])
			if(image_data[pos]==calculateValueAtPixel(row, column))
				image_data[pos]-= ((image_data[pos]).abs)*1.1
			end
		end
		image_data[pos]-= ((image_data[pos]).abs)*1.1
	end
	def findNeighbors(row, column)
		neighbors = Array.new()
		for y_offset in (-1..1)
			for x_offset in (-1..1)
				if((y_offset != 0 || x_offset != 0) && indexExists(row + y_offset, column + x_offset))
					neighbors.push([row + y_offset, column + x_offset])
				end	
			end
		end
		return neighbors
		
	end
	def indexExists(row, column)
		return !(row < 0 || row >=image_height) || (column < 0 || row >=image_width)
	end
	def self.mapTo255(input, min, max)
		if(min==0 && max == 0)
			return 0;
		end
		val = ((((input.to_f)-min)/(max-min))*255)
		return val.to_i
	end

	def self.calcColorGradient(grey)
		arr = Array.new(3)
		if(grey<64)
			arr=[255-64,grey*3,64]
		elsif(grey<128)
			grey= grey-64
			arr=[255-grey*3,255-64,64]
		elsif(grey<192)
			grey= grey-128
			arr=[64,255-64,grey*3]
		else
			grey= grey-192
			arr=[64,255-grey*3,255-64]
		end
		return arr
	end

	def self.smootherCalcColorGradient(grey)
		arr = Array.new(3)
		if(grey<64)
			arr=[255-64,grey*2+64,64]
		elsif(grey<128)
			grey= grey-64
			arr=[255-grey*2-64,255-64,64]
		elsif(grey<192)
			grey= grey-128
			arr=[64,255-64,grey*2+64]
		else
			grey= grey-192
			arr=[64,255-grey*2-64,255-64]
		end
		return arr
	end
       def self.brighterSmootherCalcColorGradient(grey)
		arr = Array.new(3)
		if(grey<64)
			arr=[255,grey*4,0]
		elsif(grey<128)
			grey= grey-64
			arr=[255-grey*4,255,0]
		elsif(grey<192)
			grey= grey-128
			arr=[0,255,grey*4]
		else
			grey= grey-192
			arr=[0,255-grey*4,255]
		end
		return arr
	end
	def self.notsomuchBrighterSmootherCalcColorGradient(grey)
		arr = Array.new(3)
		if(grey<64)
			arr=[255-32,(grey*3).to_i+32,32]
		elsif(grey<128)
			grey= grey-64
			arr=[255-(grey*3).to_i-32,255-32,32]
		elsif(grey<192)
			grey= grey-128
			arr=[32,255-32,(grey*3).to_i+32]
		else
			grey= grey-192
			arr=[32,255-(grey*3).to_i-32,255-32]
		end
		return arr
	end
			
end

app/controllers/static_pages_controller.rb
require 'image_controller'

class StaticPagesController < ApplicationController
  def home
	image_generator = ImageController.new()
	width = (params[:width].present?) ? params[:width].to_i : 400
	height = (params[:height].present?) ? params[:height].to_i : 400
	if (params[:seed].present?)
		srand(params[:seed].to_i)
	end
	image_info = image_generator.generateImage(width,height)
	@image_loc = image_info[0]
	@image_mod = image_info[1]
  end

  def help
  end  

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Hello App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/generation_data_helper.rb
module GenerationDataHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/generation_data/data.html.erb
<% provide(:title, 'All Generations') %>
<h1>All Data</h1>

<table>
  <thead><th>ID</th><th>Seed</th><th>Width</th><th>Height</th><th>River Length</th></thead>
  <tbody>
    <% @settings.each do |set| %>
    <tr>
      	<td><%= set.id %></td>
      	<td><%= set.seed %></td>
      	<td><%= set.width %></td>
      	<td><%= set.height %></td>
      	<td><%= set.river_length %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<div>
<li><%= link_to "New Image Data Entry", new_path, class: "btn btn-lg btn-primary"%></li>
</div>
<p>I really hope this page needs no introduction :)</p>
<p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer ac viverra massa. Quisque dignissim suscipit diam a aliquam. Suspendisse dui eros, consectetur sed feugiat nec, ultricies ut massa. Nulla vitae tempus neque. Maecenas vel viverra lacus. Etiam quis mauris sed orci dapibus sollicitudin. Vestibulum velit libero, volutpat ut tempor et, ullamcorper in sapien. Ut maximus nibh eget erat iaculis, ac auctor massa lacinia. Ut a tincidunt velit. Integer fringilla orci ac dui tincidunt, euismod volutpat nulla scelerisque. Nullam aliquam, risus quis egestas iaculis, mauris orci mattis tortor, at pellentesque ante felis in orci. Maecenas semper magna ac ullamcorper luctus.

Donec ullamcorper, tortor sit amet feugiat rutrum, tortor neque maximus leo, ac suscipit tortor eros nec nulla. Quisque blandit neque lectus, quis suscipit erat porttitor vitae. Donec tristique scelerisque pellentesque. Ut ullamcorper ac nisl faucibus lacinia. Nullam pulvinar lacus suscipit leo hendrerit, eget consectetur mauris rutrum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec rhoncus lacus nibh, sed lacinia nulla sagittis a. Proin ac risus mauris. Nam non libero sem. Aliquam condimentum, risus in congue facilisis, diam massa imperdiet est, eget venenatis elit sapien ac dui. Nulla in diam ac tellus porttitor dapibus. Aliquam feugiat mauris suscipit, scelerisque risus in, facilisis velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur quis mattis ipsum. Vivamus luctus ipsum sed vestibulum lobortis.

Praesent ut lacus scelerisque, lacinia turpis ac, euismod mauris. Maecenas vulputate commodo molestie. Quisque sollicitudin, leo vitae iaculis aliquet, erat nisl vulputate nulla, ut faucibus nulla metus nec tortor. Suspendisse suscipit consectetur risus vel accumsan. Suspendisse ultrices est cursus, sodales lorem sed, consectetur quam. Nulla facilisi. Aenean pharetra dignissim lacus rhoncus bibendum. Proin et elementum dui. Nulla luctus efficitur ipsum, et lobortis neque fermentum quis. Quisque pharetra tincidunt metus, vel bibendum tellus laoreet id. Quisque sed ex id erat venenatis consequat. Duis nec finibus neque. Proin euismod consectetur auctor.</p>

app/views/generation_data/new.html.erb
<% provide(:title, 'New Image') %>
<h1>Image Data</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@datum) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :seed %>
      <%= f.number_field :seed , class: 'form-control'%>

      <%= f.label :width %>
      <%= f.number_field :width , class: 'form-control'%>

      <%= f.label :height %>
      <%= f.number_field :height, class: 'form-control' %>

      <%= f.label :river_length %>
      <%= f.number_field :river_length , class: 'form-control'%>

      <%= f.submit "Store Image", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<p>If I needed paragraphs on this page it would mean I failed in its creation. I don't agree with that but I have my biases.
Enjoy your nonsense as my condolences :)</p>
<p>
Ut sed tristique massa. Nullam in lectus laoreet odio ullamcorper facilisis sodales vitae nibh. Aliquam lacus nibh, ultricies consequat posuere quis, pellentesque ut arcu. Pellentesque sit amet laoreet velit. Etiam vestibulum risus nec nunc fringilla porttitor. Nulla egestas mi quis convallis bibendum. Nullam finibus turpis magna, facilisis tincidunt dui tempor quis. Integer sollicitudin nunc id mauris ultrices commodo. Phasellus ultrices, est et placerat laoreet, dolor sapien euismod leo, vitae tincidunt nunc risus et massa. Donec facilisis tempor neque consectetur scelerisque. Curabitur eleifend quam eget ex faucibus vulputate. Vivamus ac nisl a sem vehicula efficitur. Sed auctor iaculis justo eu posuere. Vivamus in commodo mauris, id fermentum tortor.

Curabitur facilisis, risus eget efficitur luctus, tortor est commodo arcu, id dictum elit nibh ac nisi. Proin quis placerat velit. Duis in felis quis purus pharetra tempor. Nulla sit amet orci ut arcu hendrerit malesuada vitae a massa. Donec id turpis ut mauris cursus varius. Donec lacus tortor, laoreet sit amet sollicitudin a, vehicula eget purus. Praesent magna orci, sollicitudin nec molestie id, placerat id felis. Pellentesque velit lorem, venenatis nec iaculis a, convallis id augue. Vestibulum tristique, massa quis dictum consectetur, elit quam sodales nibh, at aliquet metus sapien a lectus. Morbi laoreet lectus viverra metus aliquet sodales.</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "welcome ma fellas", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Data", data_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="center jumbotron">
        <%= yield %>

        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @datum.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@datum.errors.count, "error") %>.
    </div>
    <ul>
    <% @datum.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>What all this is about</h1>
<div> 
<h2> I am currently taking <a href="https://csc324-326.sites.grinnell.edu/">this</a> course and for it I have to use Rails to build a website and deploy it to Heroku through GitHub. 
Since we needed elements of randomness and I had a personal project I had been neglecting in favor of school that used a lot of randomness it felt like a great fit. Luckily this manages to fix some of the issues I had origanlly! (like showing the images to other people in a simple fashion)</h2>
I am hoping to at some point reach a level of care and detail as the following image, but alas today is not yet the day.
</div>
<%= image_tag("example.png", alt: "A cool randomly generated island.") %>

<p> The current algorithm work using a combination of sine and cosine waves with offset frequencies to create an initial wavy structure.
Then I create an offset from the original calculated value based on distance from the center (this does not add much to the structure and initially was meant as an experiment, but in combination with the next step created beautiful images.)
The next and final step is to apply a color gradiant to every pixel which takes the current value and uses it to calculate RGB values by scaling into the 0-255 range with maximum and minimum values of the current image, that range the is split into 4 edges of the RGB cube to create transissions.
Other versions of this algorithm made use of jumps in the transitions to create interesting shapes and will be considered again in the future.</p>

<p>At the beginning of the semester, I had never worked with Ruby on Rails before. 
I went into this project with little to no web design experience but using the various tools available and the Hartl tutorial I managed to create a hopefully pleasant little site. I have dynamically created shown images, database entries, and the capability to add entries using forms. It is not seen on Heroku, but error display is also supported. 
These are all things I was unable to do at the beginning of the semester which I feel makes this website a great display of my progress.
</p>
<p> <em>MSCHIZZLE OUT!</em></p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help?</h1>
<p>Some of the intended functionality is missing, but on the home page you can view some of the generated images and on the data page you can add to a database of values that will be used to generate images in the future. There is not much to explain so please enjoy some pleasant nonsense :)</p>

<p>Duis viverra velit tellus, eu porttitor nunc venenatis id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed erat urna, bibendum nec consectetur id, porttitor ac nibh. Donec sed diam quis dolor dapibus maximus eu quis eros. Vestibulum sed metus pharetra nisl viverra feugiat. Duis lacinia, felis sit amet commodo ornare, ex eros aliquam metus, ac rhoncus tellus sem vel erat. Sed laoreet arcu porttitor mauris rutrum, et tristique nunc volutpat. Nunc sed aliquam felis. Fusce sodales neque id condimentum dignissim. Proin at nulla nibh. Integer venenatis nunc ut velit lacinia, imperdiet luctus justo tincidunt. In commodo sollicitudin imperdiet. Aenean nec pharetra neque, ac imperdiet mi. Etiam et accumsan odio. Donec ut tincidunt nulla. Aenean ornare erat vitae nunc fermentum mollis.

Vivamus mattis ante at massa tincidunt, id mollis dolor scelerisque. Pellentesque lacinia, mauris et aliquam venenatis, nibh augue hendrerit massa, laoreet feugiat velit tellus fermentum leo. Etiam convallis ut elit in sagittis. Nunc a mi volutpat, tincidunt nibh eget, faucibus neque. In metus mi, malesuada a pretium at, varius non orci. Etiam iaculis finibus velit, et commodo dui varius in. Etiam commodo justo sit amet libero dapibus, vel convallis augue tempus. Praesent odio augue, consectetur ac congue at, efficitur ut libero. Pellentesque ligula sapien, consequat eget dui id, fermentum venenatis lacus. Vivamus id odio lectus. Vivamus sed odio velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus varius auctor nisl, et bibendum mauris aliquet eget. Quisque facilisis molestie dolor quis vulputate.</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron">
  <h1>Welcome to my Random Terrain Project</h1>
<h2> The current goal of this version was to see if I can display dynamically generated images on a Heroku published website. As you can see below, hopefully, I was successful!</h2>
<h2> Right now I am using a simple algorithm to map sine and cosine waves with varying frequencies into a grey space and then map that grey space into a color gradient going from red to blue. Additionally, I also apply a modifier to each position which will reduce or increase it based on its position in the image. As artistically pleasing as it is right now, I hope to add more organic structure to it in the future.</h2>
<p> <em>MSCHIZZLE OUT!</em></p>
<em> This image was brought to you by the number <%= @image_mod %><em>
<p><img src="<%= @image_loc.to_data_url %> " alt="Image"/></p>
  <p><%= button_tag "Wanna try again", type: 'button', onclick: "window.location.reload();" , class: "btn btn-lg btn-primary" %></p>
<p>I am required by my teacher to add paragraphs, even if there is no relevant information to give. Therefore enjoy the following:</p>
<p> 
Maecenas erat libero, ultricies dapibus bibendum id, auctor eu urna. Pellentesque cursus justo ac odio commodo, eget semper nunc lobortis. Sed lobortis semper nisi, elementum feugiat lorem placerat vel. Fusce libero eros, laoreet ut dapibus sit amet, sodales nec ex. Quisque pulvinar lacus orci, eget auctor ipsum ullamcorper dictum. In hac habitasse platea dictumst. Sed vel feugiat nunc. Curabitur fermentum nibh vel lacus mattis, sed euismod libero euismod. Quisque ligula nisl, rhoncus ut lectus vel, molestie aliquet orci. Mauris non ullamcorper ante. Nulla at consectetur sem. Phasellus vulputate, enim nec hendrerit scelerisque, sapien erat tincidunt justo, id consequat nisi magna eu justo. Nulla magna nulla, vulputate id porttitor eu, ornare ac enim.

In fermentum, sem in condimentum convallis, velit mi semper nisl, ut consequat nulla lorem at elit. Curabitur felis nisi, pharetra a nulla ac, pharetra eleifend augue. Cras mi arcu, cursus non dui vel, posuere volutpat tellus. Duis et leo turpis. Suspendisse neque erat, vulputate nec rutrum vitae, tristique ut ante. In eu neque cursus, porttitor lorem ut, scelerisque lectus. Vivamus ut nisi bibendum, eleifend velit id, finibus mauris. In porta mi vitae augue ultrices, sit amet laoreet mauris ornare. Etiam vitae leo ultricies, consequat tortor quis, feugiat nibh. Cras lectus turpis, facilisis in mollis ac, pharetra at mauris. Vestibulum in tincidunt erat. Praesent ipsum ipsum, ullamcorper eu purus eu, congue porttitor mauris. Vivamus sed posuere ligula.
</p>
<p> Exciting, wasn't it?</p>
</div>



    